spring:
  application:
    name: pdf-service

server:
  port: 9000
  servlet:
    context-path: /api

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

executor:
  pool:
    corePoolSize: 3
    maxPoolSize: 6
    keepAliveSeconds: 100
    threadPrefix: 30

logging:
  level:
    org:
      springframework: INFO

management:
  endpoints:
    enabled-by-default: true

webdriver:
  chrome:
    driver: C:/Programs/bin/chromedriver.exe
    binary: C:/Programs/chrome87/chrome.exe
  timeouts:
    conditionalDelay:
      pollingEverySeconds: 5
      maxSeconds: 60
    fixedDelay:
      maxSeconds: 60